name: Automated Python 1

on:
  push:
    branches: # adjust
      - main
  schedule:
    - cron: '0 21 * * *' # This is 05:00 AM Thailand time (UTC+7+1) in UTC time test
    - cron: '0 22 * * *'   # 22:00 UTC
    - cron: '0 23 * * *'   # 23:00 UTC
    - cron: '0 0 * * *'    # 00:00 UTC
    - cron: '0 1 * * *'    # 01:00 UTC
jobs:
  autoscrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Using Python 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyarrow  # Add pyarrow here for Parquet file handling
        pip install gspread oauth2client pandas selenium webdriver-manager gspread_dataframe

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} 

    - name: Run Automated script
      run: python manual-system-f1-th-ver2.py # THIS WORK!.
      
    # - name: Run backup S50 script
    #   run: python automate-S50.py   

    # - name: Run backup USD script
    #   run: python automate-USD.py    

    # - name: Run backup GF10 script
    #   run: python automate-GF10.py   
      
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        #git add *.parquet  # Add all .parquet files in the root directory test
        # Check if there are changes. If there are, commit them.
        if git diff --staged --quiet; then
          echo "No changes to commit."
        else
          git commit -m "GH ACTION Updated Data $(date)"
          git push
        fi
      env:
        REPO_KEY: ${{ secrets.GITHUB_TOKEN }}  # Ensure this matches the secret name
