name: Automated Python

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/3 * * * *'  # Run every 3 minutes

jobs:
  autoscrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Using Python 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyarrow  # Add pyarrow here for Parquet file handling
        pip install gspread oauth2client pandas selenium webdriver-manager gspread_dataframe

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}  # Ensure this matches the secret name 

    - name: Run Python script
      run: python test_google_credentials.py  # Ensure script name matches your script's filename test

    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add data/*  # Adjust this path if your data directory differs
        git commit -m "GH ACTION Updated Data $(date)"
        git push
      env:
        REPO_KEY: ${{ secrets.GITHUB_TOKEN }}  # Ensure this matches the secret name
