- name: Set up Python
  uses: actions/setup-python@v5
  with:
    python-version: '3.9'

- name: Install deps
  run: |
    python -m pip install --upgrade pip
    pip install pandas gspread google-auth gspread_dataframe

- name: Authenticate to Google Cloud
  uses: google-github-actions/auth@v2
  with:
    credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

- name: Run date consistency check
  env:
    MARKET_INPUT_URL: "https://docs.google.com/spreadsheets/d/17SMA52gIOkjFan-0au_YJEAxoWIzoNA84qlmgoTsZ-s/edit#gid=1037340594"
    MARKET_DATA_URL: "https://docs.google.com/spreadsheets/d/19Rj7iW5xWOe6ZJJRsO9VzsZXyLfFu1S_vtClEE_3DEw/edit#gid=748449431"
    HOLDING_SHEET_NAME: "holding_information"
    # GOOGLE_APPLICATION_CREDENTIALS is set by the auth step
  run: python scripts/check_gsheets_dates.py
